/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

const Island=(props)=> {
  const { nodes, materials } = useGLTF('/ImageToStl.com_main website.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.087, 0, 0.153]} rotation={[2.989, 0.454, -2.642]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Truck.geometry}
          material={materials['tripo_mat_5aa22d95-f484-4906-90c2-1aa75a99fa38']}
          position={[42.91, -145.174, -829.105]}
          rotation={[1.42, -0.428, 3.078]}
          scale={0.842}
        />
      </group>
      <group position={[4.033, 0, 1.034]} rotation={[-Math.PI, -0.797, 0]} scale={0}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.banner.geometry}
          material={nodes.banner.material}
          position={[-22027.207, -10407.456, -69499.242]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.banner001.geometry}
          material={nodes.banner001.material}
          position={[-20613.008, -9058.585, -81299.563]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape003.geometry}
        material={materials.grass}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.black}
        position={[0, -0.173, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Untitled.geometry}
        material={materials['palette.002']}
        position={[0.107, 0.057, 6.167]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.257}
      />
      <group position={[-6.394, 0.015, -5.171]} rotation={[Math.PI / 2, 0, 2.208]} scale={0}>
        <group position={[1729.996, -6329.438, -7690.001]}>
          <group
            position={[-1712.397, 6417.836, 7626.905]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group position={[172369.719, -762670.688, 640333.875]} scale={[8, 1, 6]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_396.geometry}
                material={materials.material_10}
                position={[-21544.873, 762673.563, -106722.219]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.01, 0.002, 0.06]}
              />
            </group>
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_159.geometry}
          material={materials.material_6}
          position={[5423.439, -4750.717, -1383.016]}
          rotation={[-0.354, 0.913, -1.134]}
          scale={[1, 1, 97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_161.geometry}
          material={materials.material_7}
          position={[-5079.098, -7564.859, -1863.717]}
          rotation={[0.354, -0.913, 2.008]}
          scale={[1, 1, 94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_163.geometry}
          material={materials.material_8}
          position={[-8822.476, -8567.898, 899.495]}
          rotation={[0, 0, 1.833]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_165.geometry}
          material={materials.material_8}
          position={[9322.442, -3705.979, 1294.159]}
          rotation={[0, 0, 1.833]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_168.geometry}
          material={materials.material_6}
          position={[4037.218, -9924.168, -1777.68]}
          rotation={[0.79, 0.618, -2.621]}
          scale={[1, 1, 97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_174.geometry}
          material={materials.material_8}
          position={[6891.493, -12778.438, 899.495]}
          rotation={[0, 0, Math.PI / 4]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_177.geometry}
          material={materials.material_6}
          position={[1636.216, -11310.395, -1777.68]}
          rotation={[0.944, 0.214, -2.989]}
          scale={[1, 1, 97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_179.geometry}
          material={materials.material_8}
          position={[-2180.975, -15209.395, 899.495]}
          rotation={[0, 0, -0.262]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_181.geometry}
          material={materials.material_8}
          position={[2680.947, -15209.396, 899.495]}
          rotation={[0, 0, 0.262]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_183.geometry}
          material={materials.material_6}
          position={[-1136.237, -11310.389, -1777.681]}
          rotation={[0.944, -0.214, 2.989]}
          scale={[1, 1, 97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_188.geometry}
          material={materials.material_7}
          position={[-3651.176, -10038.104, -1863.717]}
          rotation={[0.79, -0.618, 2.621]}
          scale={[1, 1, 94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_190.geometry}
          material={materials.material_8}
          position={[-6391.511, -12778.438, 899.495]}
          rotation={[0, 0, 2.356]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_195.geometry}
          material={materials.material_6}
          position={[5423.437, -7523.152, -2096.911]}
          rotation={[0.354, 0.913, -2.008]}
          scale={[1, 1, 97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_197.geometry}
          material={materials.material_7}
          position={[-5079.094, -4709.014, -1303.214]}
          rotation={[-0.354, -0.913, 1.134]}
          scale={[1, 1, 94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_199.geometry}
          material={materials.material_8}
          position={[-8822.466, -3705.98, 1459.999]}
          rotation={[0, 0, 1.309]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_201.geometry}
          material={materials.material_8}
          position={[9322.45, -8567.892, 899.495]}
          rotation={[0, 0, 1.309]}
          scale={[5.9, 5.9, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_204.geometry}
          material={materials.material_9}
          position={[259.986, -6309.441, 1499.999]}
          scale={[71.8, 71.8, 1.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_207.geometry}
          material={materials.material_10}
          position={[-1455.014, -3321.648, 29.999]}
          rotation={[-0.152, -0.087, 0.517]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_209.geometry}
          material={materials.material_4}
          position={[-624.231, -9644.117, 29.999]}
          rotation={[0.169, -0.045, -0.258]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_211.geometry}
          material={materials.material_10}
          position={[269.986, -9759.443, 29.999]}
          rotation={[0.175, 0, 0]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_213.geometry}
          material={materials.material_4}
          position={[1162.909, -9641.875, 29.999]}
          rotation={[0.169, 0.045, 0.258]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_215.geometry}
          material={materials.material_10}
          position={[1994.982, -9297.225, 29.999]}
          rotation={[0.152, 0.087, 0.517]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_218.geometry}
          material={materials.material_10}
          position={[-1455.018, -9297.225, 29.999]}
          rotation={[0.152, -0.087, -0.517]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_220.geometry}
          material={materials.material_10}
          position={[1994.988, -3321.645, 29.999]}
          rotation={[-0.152, 0.087, -0.517]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_223.geometry}
          material={materials.material_10}
          position={[3719.99, -6309.443, 29.999]}
          rotation={[0, 0.175, Math.PI / 2]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_225.geometry}
          material={materials.material_10}
          position={[-3180.012, -6309.438, 29.999]}
          rotation={[0, -0.175, Math.PI / 2]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_228.geometry}
          material={materials.material_10}
          position={[3257.767, -8034.443, 29.999]}
          rotation={[0.088, 0.151, 1.041]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_230.geometry}
          material={materials.material_10}
          position={[-2717.8, -4584.438, 29.999]}
          rotation={[-0.088, -0.151, 1.041]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_233.geometry}
          material={materials.material_10}
          position={[-2717.798, -8034.439, 29.999]}
          rotation={[0.088, -0.151, -1.041]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_235.geometry}
          material={materials.material_10}
          position={[3257.769, -4584.443, 29.999]}
          rotation={[-0.088, 0.151, -1.041]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_238.geometry}
          material={materials.material_4}
          position={[2709.501, -8746.373, 29.999]}
          rotation={[0.124, 0.123, 0.778]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_240.geometry}
          material={materials.material_4}
          position={[-2169.536, -3867.342, 29.999]}
          rotation={[-0.124, -0.123, 0.778]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_243.geometry}
          material={materials.material_4}
          position={[-3070.823, -5418.758, 29.999]}
          rotation={[-0.046, -0.169, -1.836]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_245.geometry}
          material={materials.material_4}
          position={[3594.064, -7204.604, 29.999]}
          rotation={[0.046, 0.169, -1.836]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_248.geometry}
          material={materials.material_4}
          position={[-3068.585, -7205.895, 29.999]}
          rotation={[0.046, -0.169, -1.305]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_250.geometry}
          material={materials.material_4}
          position={[3596.31, -5420.045, 29.999]}
          rotation={[-0.046, 0.169, -1.305]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_253.geometry}
          material={materials.material_4}
          position={[-2173.073, -8752.498, 29.999]}
          rotation={[0.124, -0.123, -0.778]}
          scale={[9.2, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_255.geometry}
          material={materials.material_4}
          position={[2705.968, -3873.453, 29.999]}
          rotation={[-0.124, 0.123, -0.778]}
          scale={[9.4, 1, 31]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_259.geometry}
          material={materials.material_10}
          position={[2219.978, -9686.934, -2270.003]}
          rotation={[0, 0, Math.PI / 6]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_261.geometry}
          material={materials.material_10}
          position={[2219.978, -9686.934, -1570.002]}
          rotation={[Math.PI, 0, -2.094]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_263.geometry}
          material={materials.material_10}
          position={[-1680.008, -2931.941, -1570.002]}
          rotation={[Math.PI, 0, -2.094]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_265.geometry}
          material={materials.material_10}
          position={[-1680.008, -2931.941, -2270.003]}
          rotation={[0, 0, Math.PI / 6]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_267.geometry}
          material={materials.material_10}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, Math.PI / 6]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_270.geometry}
          material={materials.material_10}
          position={[3647.492, -8259.438, -2270.003]}
          rotation={[0, 0, Math.PI / 3]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_272.geometry}
          material={materials.material_10}
          position={[3647.492, -8259.438, -1570.002]}
          rotation={[Math.PI, 0, -2.618]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_274.geometry}
          material={materials.material_10}
          position={[-3107.518, -4359.439, -1570.002]}
          rotation={[-Math.PI, 0, -2.618]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_276.geometry}
          material={materials.material_10}
          position={[-3107.518, -4359.439, -2270.003]}
          rotation={[0, 0, Math.PI / 3]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_278.geometry}
          material={materials.material_10}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, Math.PI / 3]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_281.geometry}
          material={materials.material_10}
          position={[4169.986, -6309.439, -2270.003]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_283.geometry}
          material={materials.material_10}
          position={[4169.986, -6309.439, -1570.002]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_285.geometry}
          material={materials.material_10}
          position={[-3630.018, -6309.439, -1570.002]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_287.geometry}
          material={materials.material_10}
          position={[-3630.018, -6309.439, -2270.003]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_289.geometry}
          material={materials.material_10}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_292.geometry}
          material={materials.material_10}
          position={[3647.488, -4359.443, -2270.003]}
          rotation={[0, 0, 2.094]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_294.geometry}
          material={materials.material_10}
          position={[3647.488, -4359.443, -1570.002]}
          rotation={[Math.PI, 0, 2.618]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_296.geometry}
          material={materials.material_10}
          position={[-3107.518, -8259.438, -1570.002]}
          rotation={[Math.PI, 0, 2.618]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_298.geometry}
          material={materials.material_10}
          position={[-3107.518, -8259.438, -2270.003]}
          rotation={[0, 0, 2.094]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_300.geometry}
          material={materials.material_10}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 2.094]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_303.geometry}
          material={materials.material_10}
          position={[2219.98, -2931.938, -2270.003]}
          rotation={[0, 0, 2.618]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_305.geometry}
          material={materials.material_10}
          position={[2219.98, -2931.938, -1570.002]}
          rotation={[Math.PI, 0, 2.094]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_307.geometry}
          material={materials.material_10}
          position={[-1680.008, -9686.945, -1570.002]}
          rotation={[Math.PI, 0, 2.094]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_309.geometry}
          material={materials.material_10}
          position={[-1680.008, -9686.945, -2270.003]}
          rotation={[0, 0, 2.618]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_311.geometry}
          material={materials.material_10}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 2.618]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_314.geometry}
          material={materials.material_10}
          position={[269.992, -10209.441, -2270.003]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_316.geometry}
          material={materials.material_10}
          position={[269.992, -10209.441, -1570.002]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_318.geometry}
          material={materials.material_10}
          position={[269.984, -2409.443, -1570.002]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_320.geometry}
          material={materials.material_10}
          position={[269.984, -2409.443, -2270.003]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_322.geometry}
          material={materials.material_10}
          position={[269.986, -6309.439, -5270.003]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_325.geometry}
          material={materials.material_11}
          position={[1279.372, -10076.549, -2270.003]}
          rotation={[0, 0, 0.262]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_327.geometry}
          material={materials.material_11}
          position={[1279.376, -10076.551, -1570.002]}
          rotation={[Math.PI, 0, -1.833]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_329.geometry}
          material={materials.material_11}
          position={[-739.415, -2542.324, -1570.002]}
          rotation={[Math.PI, 0, -1.833]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_331.geometry}
          material={materials.material_11}
          position={[-739.415, -2542.324, -2270.003]}
          rotation={[0, 0, 0.262]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_333.geometry}
          material={materials.material_11}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 0.262]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_336.geometry}
          material={materials.material_11}
          position={[1279.37, -2542.324, -2270.003]}
          rotation={[0, 0, 2.88]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_338.geometry}
          material={materials.material_11}
          position={[1279.374, -2542.328, -1570.002]}
          rotation={[Math.PI, 0, 1.833]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_340.geometry}
          material={materials.material_11}
          position={[-739.407, -10076.547, -1570.002]}
          rotation={[Math.PI, 0, 1.833]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_342.geometry}
          material={materials.material_11}
          position={[-739.407, -10076.547, -2270.003]}
          rotation={[0, 0, 2.88]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_344.geometry}
          material={materials.material_11}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 2.88]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_347.geometry}
          material={materials.material_11}
          position={[3027.701, -3551.727, -2270.003]}
          rotation={[0, 0, 2.356]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_349.geometry}
          material={materials.material_11}
          position={[3027.701, -3551.727, -1570.002]}
          rotation={[Math.PI, 0, 2.356]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_351.geometry}
          material={materials.material_11}
          position={[-2487.725, -9067.15, -1570.002]}
          rotation={[Math.PI, 0, 2.356]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_353.geometry}
          material={materials.material_11}
          position={[-2487.725, -9067.15, -2270.003]}
          rotation={[0, 0, 2.356]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_355.geometry}
          material={materials.material_11}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 2.356]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_358.geometry}
          material={materials.material_11}
          position={[4037.093, -5300.039, -2270.003]}
          rotation={[0, 0, 1.833]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_360.geometry}
          material={materials.material_11}
          position={[4037.093, -5300.039, -1570.002]}
          rotation={[-Math.PI, 0, 2.88]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_362.geometry}
          material={materials.material_11}
          position={[-3497.129, -7318.836, -1570.002]}
          rotation={[-Math.PI, 0, 2.88]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_364.geometry}
          material={materials.material_11}
          position={[-3497.129, -7318.836, -2270.003]}
          rotation={[0, 0, 1.833]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_366.geometry}
          material={materials.material_11}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 1.833]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_369.geometry}
          material={materials.material_11}
          position={[4037.099, -7318.836, -2270.003]}
          rotation={[0, 0, 1.309]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_371.geometry}
          material={materials.material_11}
          position={[4037.099, -7318.836, -1570.002]}
          rotation={[-Math.PI, 0, -2.88]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_373.geometry}
          material={materials.material_11}
          position={[-3497.127, -5300.045, -1570.002]}
          rotation={[-Math.PI, 0, -2.88]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_375.geometry}
          material={materials.material_11}
          position={[-3497.127, -5300.045, -2270.003]}
          rotation={[0, 0, 1.309]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_377.geometry}
          material={materials.material_11}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, 1.309]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_380.geometry}
          material={materials.material_11}
          position={[3027.699, -9067.156, -2270.003]}
          rotation={[0, 0, Math.PI / 4]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_382.geometry}
          material={materials.material_11}
          position={[3027.699, -9067.156, -1570.002]}
          rotation={[Math.PI, 0, -2.356]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_384.geometry}
          material={materials.material_11}
          position={[-2487.731, -3551.727, -1570.002]}
          rotation={[Math.PI, 0, -2.356]}
          scale={[2, 10, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_386.geometry}
          material={materials.material_11}
          position={[-2487.731, -3551.727, -2270.003]}
          rotation={[0, 0, Math.PI / 4]}
          scale={[10, 2, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_388.geometry}
          material={materials.material_11}
          position={[269.986, -6309.439, -5270.003]}
          rotation={[0, 0, Math.PI / 4]}
          scale={[10, 80, 50]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_391.geometry}
          material={materials.material_4}
          position={[299.994, -6329.44, -7690.001]}
          scale={[2, 2, 37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_394.geometry}
          material={materials.material_10}
          position={[2859.988, -6309.438, -8540.002]}
          rotation={[-Math.PI, 0, 0]}
          scale={[8, 1, 6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_398.geometry}
          material={materials.material_10}
          position={[1359.994, -6309.438, -8840.003]}
          scale={[22, 1, 12]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree.geometry}
        material={materials['tree bark']}
        position={[11.818, 0.138, 9.056]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials['Material.009']}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.petals}
        position={[-5.037, -0.24, 5.784]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group position={[-5.037, -0.24, 5.784]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials.grass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials.bud}
        />
      </group>
      <group position={[3.739, 0.093, 2.346]} rotation={[0, 1.057, 0]} scale={0}>
        <group position={[-0.076, -0.001, 0.024]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.068, -0.034, -0.004]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group
              position={[-4.302, -85895.414, 623.585]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['concert-stagemainfinal__0'].geometry}
                material={materials['Scene_-_Root']}
                position={[-5.328, -23.104, 863.512]}
                rotation={[Math.PI / 2, -0.141, 0]}
                scale={0.008}
              />
            </group>
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.003']}
        rotation={[Math.PI / 2, 0, 2.498]}
        scale={0}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.006']}
          position={[10725.53, 2902.096, 344.627]}
          rotation={[0, 0, Math.PI]}
          scale={[-0.625, -31.75, -0.372]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials['Material.007']}
          position={[10725.529, 2902.097, 344.628]}
          rotation={[0, 0, Math.PI]}
          scale={[-0.199, -31.115, -0.372]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Counter.geometry}
        material={materials.material_37}
        position={[-5.144, -0.068, -5.613]}
        rotation={[Math.PI / 2, 0, 1.593]}
        scale={[0.003, 0, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1000.geometry}
          material={materials.material_40}
          position={[0.333, 14.999, -261.111]}
          scale={[1, 1.833, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1002.geometry}
          material={materials.material_40}
          position={[0.333, -351.669, -261.111]}
          scale={[1, 1.833, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_871.geometry}
          material={materials.material_35}
          position={[45.333, -243.334, -338.889]}
          scale={[0.033, 7, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_873.geometry}
          material={materials.material_35}
          position={[0.333, -243.336, -300]}
          scale={[0.933, 7, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_875.geometry}
          material={materials.material_35}
          position={[0.333, -243.336, -377.778]}
          scale={[0.933, 7, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_879.geometry}
          material={materials.material_36}
          position={[-7.853, 69.999, -313.537]}
          rotation={[1.099, 0.237, -2.396]}
          scale={[0.19, 0.219, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_881.geometry}
          material={materials.material_36}
          position={[-8.88, 69.997, -352.671]}
          rotation={[1.099, 0.237, 0.746]}
          scale={[0.19, 0.219, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_883.geometry}
          material={materials.material_36}
          position={[-14.237, 69.999, -331.392]}
          rotation={[1.063, -0.174, -0.824]}
          scale={[0.219, 0.19, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_885.geometry}
          material={materials.material_36}
          position={[-21.001, 43.33, -334.811]}
          rotation={[0, -1.571, 0]}
          scale={[0.556, 1.333, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_887.geometry}
          material={materials.material_36}
          position={[7.748, 43.329, -325.41]}
          rotation={[0, -0.788, 0]}
          scale={[0.311, 1.333, 0.075]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_889.geometry}
          material={materials.material_36}
          position={[1.333, 43.332, -334.811]}
          rotation={[0, -1.571, 0]}
          scale={[0.556, 1.333, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_891.geometry}
          material={materials.material_36}
          position={[5.752, 43.332, -343.512]}
          rotation={[Math.PI, -0.742, Math.PI]}
          scale={[0.333, 1.333, 0.081]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_893.geometry}
          material={materials.material_36}
          position={[16.666, 43.333, -334.811]}
          rotation={[0, -1.571, 0]}
          scale={[0.556, 1.333, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_895.geometry}
          material={materials.material_36}
          position={[20.833, 43.332, -357.033]}
          scale={[0.11, 1.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_897.geometry}
          material={materials.material_36}
          position={[20.166, 43.332, -334.811]}
          scale={[0.097, 1.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_899.geometry}
          material={materials.material_36}
          position={[20.833, 43.332, -312.589]}
          scale={[0.11, 1.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_901.geometry}
          material={materials.material_36}
          position={[-31.667, 43.332, -334.811]}
          rotation={[0, -1.571, 0]}
          scale={[0.556, 1.333, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_903.geometry}
          material={materials.material_36}
          position={[-31.667, 43.332, -357.033]}
          scale={[0.133, 1.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_905.geometry}
          material={materials.material_36}
          position={[34.999, 43.331, -357.033]}
          scale={[0.133, 1.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_907.geometry}
          material={materials.material_36}
          position={[34.999, 43.331, -334.811]}
          rotation={[0, -1.571, 0]}
          scale={[0.556, 1.333, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_909.geometry}
          material={materials.material_35}
          position={[0.333, -243.336, -411.111]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[7, 0.6, 1.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_911.geometry}
          material={materials.material_35}
          position={[-44.667, -243.337, -338.889]}
          scale={[0.033, 7, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_913.geometry}
          material={materials.material_35}
          position={[0.333, -243.336, -338.889]}
          scale={[0.933, 6.667, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_916.geometry}
          material={materials.material_30}
          position={[0, -355.001, -88.889]}
          scale={[0.933, 4.767, 2.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_918.geometry}
          material={materials.material_37}
          position={[0, -600.002, -88.889]}
          scale={[1, 0.333, 2.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_920.geometry}
          material={materials.material_37}
          position={[34.999, -0.003, -88.889]}
          scale={[0.3, 1, 2.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_922.geometry}
          material={materials.material_37}
          position={[-48.334, -283.335, -88.889]}
          scale={[0.033, 6.667, 2.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_924.geometry}
          material={materials.material_37}
          position={[-35, -0.003, -88.889]}
          scale={[0.3, 1, 2.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_928.geometry}
          material={materials.material_37}
          position={[48.333, -283.336, -88.889]}
          scale={[0.033, 6.667, 2.778]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_931.geometry}
          material={materials.material_37}
          position={[0.333, -535.005, -261.111]}
          scale={[1, 1.833, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_933.geometry}
          material={materials.material_37}
          position={[0.333, -168.337, -261.111]}
          scale={[1, 1.833, 0.667]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_937.geometry}
          material={materials.material_38}
          position={[31.999, 139.999, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_941.geometry}
          material={materials.material_37}
          position={[44.499, 123.33, -199.444]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.117, 0.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_943.geometry}
          material={materials.material_37}
          position={[44.499, 123.33, -250]}
          scale={[0.117, 0.333, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_946.geometry}
          material={materials.material_39}
          position={[31.999, 123.331, -244.444]}
          scale={[0.133, 0.333, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_948.geometry}
          material={materials.material_39}
          position={[31.999, 123.331, -183.333]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.133, 0.444]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_950.geometry}
          material={materials.material_38}
          position={[44.666, 139.997, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_953.geometry}
          material={materials.material_38}
          position={[-43.001, 139.998, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_957.geometry}
          material={materials.material_37}
          position={[-30.5, 123.329, -199.444]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.117, 0.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_959.geometry}
          material={materials.material_37}
          position={[-30.5, 123.329, -250]}
          scale={[0.117, 0.333, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_962.geometry}
          material={materials.material_39}
          position={[-43.001, 123.332, -244.444]}
          scale={[0.133, 0.333, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_964.geometry}
          material={materials.material_39}
          position={[-43.001, 123.332, -183.333]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.133, 0.444]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_966.geometry}
          material={materials.material_38}
          position={[-30.334, 139.996, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_969.geometry}
          material={materials.material_38}
          position={[-18, 139.998, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_973.geometry}
          material={materials.material_37}
          position={[-5.501, 123.332, -199.444]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.117, 0.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_975.geometry}
          material={materials.material_37}
          position={[-5.501, 123.332, -250]}
          scale={[0.117, 0.333, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_978.geometry}
          material={materials.material_39}
          position={[-18, 123.329, -244.444]}
          scale={[0.133, 0.333, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_980.geometry}
          material={materials.material_39}
          position={[-18, 123.329, -183.333]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.133, 0.444]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_982.geometry}
          material={materials.material_38}
          position={[-5.334, 139.996, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_985.geometry}
          material={materials.material_38}
          position={[7, 139.997, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_989.geometry}
          material={materials.material_37}
          position={[19.499, 123.332, -199.444]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.117, 0.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_991.geometry}
          material={materials.material_37}
          position={[19.499, 123.332, -250]}
          scale={[0.117, 0.333, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_994.geometry}
          material={materials.material_39}
          position={[6.999, 123.331, -244.444]}
          scale={[0.133, 0.333, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_996.geometry}
          material={materials.material_39}
          position={[6.999, 123.331, -183.333]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[0.333, 0.133, 0.444]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_998.geometry}
          material={materials.material_38}
          position={[19.666, 140, -277.778]}
          scale={[0.033, 0.333, 0.111]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_main website.glb')
export default Island;
